language: ruby
rvm:
  - ruby-2.1.9
  - ruby-2.2.5
  - ruby-2.3.1
  - ruby-head
  - rubinius-3.62
  - rubinius
  - jruby-9.0.5.0
  - jruby-head
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius
sudo: required
dist: trusty
